#!/usr/bin/env bash

function main {
  local nm_lock="$1"; shift
  local digest="$1"; shift

  while true; do
    if ddlock acquire "$nm_lock" "$digest"; then
      "$@" || true
      ddlock leave "$nm_lock"
      break
    fi

    sleep 1
  done
}

source sub "$BASH_SOURCE" "$@"
