#!/usr/bin/env bash

function main {
  local nm_lock="$1"; shift
  local digest="$1"; shift

  while true; do
    if aws dynamodb put-item \
      --table terraform_state_lock \
      --item "$(jq -n --arg lock "$nm_lock" --arg digest "$digest" '{LockID: {S: $lock}, Digest: {S: $digest}}')" \
      --condition-expression '#lock <> :lock OR (#lock = :lock AND #digest = :digest)' \
      --expression-attribute-names "$(jq -n '{"#lock": "LockID", "#digest": "Digest"}')" \
      --expression-attribute-values "$(jq -n --arg lock "$nm_lock" --arg digest "$digest" '{":lock": {S: $lock}, ":digest": {S: $digest}}')"; then
    
      "$@" || true
      ddlock leave "$nm_lock"
      break
    fi

    sleep 1
  done
}

source sub "$BASH_SOURCE" "$@"
