#!/usr/bin/env bash

function main {
  local nm_lock="$1"; shift
  local digest="$1"; shift

  while true; do
    if ddlock acquire "$nm_lock" "$digest"; then
      trap "ddlock leave $nm_lock" EXIT
      "$@" || true
      break
    fi

    sleep 1
  done
}

source sub "$BASH_SOURCE" "$@"
