#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      pkg ensure sysutils/lockf
      ;;
    Linux)
      sudo -E aptitude install -y run-one
      ;;
  esac
}

bootstrap
