#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Darwin)
      if ! type -P lockf >/dev/null; then
        return 0
      fi
      ;;
    Ubuntu|Amazon)
      if ! type -P flock >/dev/null; then
        return 0
      fi
      ;;
  esac

  return 1
}

bootstrap
