#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  return 0 # TODO figure out what to do with these lock commands

  case "${DISTRIB_ID}" in
    Darwin)
      if ! type -P lockf >/dev/null; then
        return 0
      fi
      ;;
    *)
      if ! type -P flock >/dev/null; then
        return 0
      fi
      ;;
  esac

  return 1
}

bootstrap
