#!/usr/bin/env bash

function bootstrap {
  local shome="${_lock_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      if [[ -x "$(which lockf 2>/dev/null || true)" ]]; then
        return 0
      fi
      ;;
    Linux)
      if [[ -x "$(which flock 2>/dev/null || true)" ]]; then
        return 0
      fi
      ;;
  esac

  return 1
}

bootstrap
